packages:
  - apps/*
  - packages/*
  - examples/*

allowBuilds:
  '@foundry-rs/anvil': true
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
  unrs-resolver: true

overrides:
  '@esbuild-kit/core-utils@3.3.2>esbuild': 0.25.12
  baseline-browser-mapping: 2.11.12
  electron-to-chromium: 1.5.402
  mppx: 0.4.11
