import { randomBytes } from "node:crypto";
import { appendFile, open, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { privateKeyToAccount } from "viem/accounts";

const envPath = resolve(import.meta.dirname, "../.env.local");

function createWallet() {
  for (;;) {
    const privateKey = `0x${randomBytes(32).toString("hex")}`;
    try {
      const account = privateKeyToAccount(privateKey);
      return { address: account.address, privateKey };
    } catch {
      // The secp256k1 invalid-key probability is negligible; retry safely.
    }
  }
}

function renderEnv(wallets, mppSecret) {
  return `# Generated by pnpm env:dev. Never commit or share this file.
# Fill these from the OKX Developer Portal.
OKX_API_KEY=
OKX_SECRET_KEY=
OKX_PASSPHRASE=

# Local PostgreSQL default. Change this if your database differs.
DATABASE_URL=postgresql://cobia:cobia@127.0.0.1:5432/cobia

# Solver signing and payment-recipient wallet.
# Deterministic solver: ${wallets.deterministic.address}
DETERMINISTIC_SOLVER_PRIVATE_KEY=${wallets.deterministic.privateKey}

# Seller payment state and the recoverable 10% protocol treasury.
MPPX_SECRET_KEY=${mppSecret}
COBIA_TREASURY=${wallets.treasury.address}
COBIA_DEV_TREASURY_PRIVATE_KEY=${wallets.treasury.privateKey}
PAYMENT_REALM=localhost:3000

# X Layer RPC endpoints.
XLAYER_RPC_URL=https://rpc.xlayer.tech
XLAYER_TESTNET_RPC_URL=https://testrpc.xlayer.tech/terigon
`;
}

async function migrateExistingEnv() {
  let content;
  try {
    content = await readFile(envPath, "utf8");
  } catch (error) {
    if (error?.code === "ENOENT") return false;
    throw error;
  }
  if (/^PAYMENT_REALM=/m.test(content)) {
    console.error(`Refusing to overwrite existing ${envPath}`);
    process.exitCode = 1;
    return true;
  }
  const separator = content.endsWith("\n") ? "" : "\n";
  await appendFile(envPath, `${separator}PAYMENT_REALM=localhost:3000\n`, "utf8");
  console.log(`Added missing non-secret PAYMENT_REALM to existing ${envPath}`);
  return true;
}

if (!await migrateExistingEnv()) {
  const wallets = {
    deterministic: createWallet(),
    treasury: createWallet(),
  };
  const mppSecret = randomBytes(32).toString("hex");
  let file;
  try {
    file = await open(envPath, "wx", 0o600);
    await file.writeFile(renderEnv(wallets, mppSecret), { encoding: "utf8" });
  } finally {
    await file?.close();
  }
  console.log(`Created ${envPath}`);
  console.log(`Deterministic solver: ${wallets.deterministic.address}`);
  console.log(`Dev treasury:         ${wallets.treasury.address}`);
  console.log("Private keys were written only to the ignored env file.");
}
